version: "3.7"
services:

  db-server:
    image: mysql:latest
    container_name: sql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin_container
    restart: always
    environment:
      PMA_HOST: db-server
    links:
      - db-server
    ports:
      - "8081:80"